package me.kowo.opencity.eventbus;

public enum EventMessage {
    ON_QUERY_TEXT_SUBMIT,
    ON_QUERY_TEXT_CHANGE,
    ON_CATEGORIES_RECEIVED,
    GET_CURRENT_LOCATION,
    ON_SEARCH_PLACES_RECEIVED,
    ON_PLACES_RECEIVED,
    ON_DETAILED_INFO_RECEIVED,
    ON_INTERNET_CONNECTED,
    SELECT_ITEM
}
